Add support for p256
mcginty/snow pull request #185
Opened 2024-09-28 22:00 UTC by AlfioEmanueleFresta

## Changes

* Adds support for NIST P-256, aka secp256r1, using the [p256 crate from RustCrypto](https://github.com/RustCrypto/elliptic-curves/tree/master/p256). This is a pure-Rust implementation.
* As per feedback in previous abandoned PR https://github.com/mcginty/snow/pull/38#issuecomment-435416354, the code is feature gated, as this is a non-standard curve.

## Motivation

This curve is used for the Noise handshake in [CTAP2 Hybrid Transport](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#hybrid-qr-initiated). This is the protocol used for browsers to access credentials on roaming authenticators connected over the internet (e.g. phones running Android and iOS). 

I'm using snow in my implementation of CTAP2, aimed at bringing Passkeys to the Linux desktop, see [xdg-credentials-portal](https://github.com/AlfioEmanueleFresta/xdg-credentials-portal).

## Tests

All commands below succeed:

```
$ cargo build --all-targets
$ cargo build --all-targets --features p256
$ cargo test --all-targets
$ cargo test --all-targets --features p256
```

2025-02-12 22:18 UTC, AlfioEmanueleFresta commented
Friendy ping on this @mcginty - I would need this change to be upstreamed so we can begin publishing [linux-credentials/libwebauthn](https://github.com/linux-credentials/libwebauthn) to crates.io. TIA!

2025-02-13 16:33 UTC, mcginty commented
@AlfioEmanueleFresta Wow, I'm so sorry I dropped the ball on this! Reviewing now.

2025-02-13 16:52 UTC, mcginty requested changes
Thanks for the PR! This is looking pretty good, I just have some small comments/questions.

2025-02-13 16:52 UTC, mcginty commented on src/constants.rs
> +pub const MAXDHLEN: usize = 65;
```suggestion
// P-256 uncompressed SEC-1 encodings are 65 bytes long, larger than the `MAXDHLEN` in the official Noise spec.
#[cfg(feature = "p256")]
pub const MAXDHLEN: usize = 65;

// Curve448 keys are the largest in the official Noise spec.
#[cfg(not(feature = "p256"))]
pub const MAXDHLEN: usize = 56;
```

2025-02-13 16:52 UTC, mcginty commented on src/resolvers/default.rs
> +    privkey: [u8; 32],
Any reason not to store `privkey` as a `p256::SecretKey` here?

2025-02-13 16:52 UTC, mcginty commented on src/resolvers/default.rs
> +        );
Where did you get these test constants from? It would be good to have a citation to a known-good example to derive trust for this implementation.

2025-02-13 16:52 UTC, mcginty requested changes
Thanks for the PR! This is looking pretty good, I just have some small comments/questions.

2025-02-13 17:05 UTC, complexspaces commented
As a drive-by comment, which might be helpful context: I asked Trevor at RWC one year what his thoughts were on CTAP Hybrid being specified with a non-standard Noise curve, as the designer of Noise, and the answer was that it wasn't a big deal these days and that maybe future versions of Noise would be more curve agnostic anyway.

Tl;dr I think this change is worthwhile for sure :)

2025-02-13 18:35 UTC, mcginty commented
@complexspaces thanks for the context! Yeah, generally I'm open to snow supporting "unofficial" general-use Noise modes, as long as the default snow only exposes the officially supported modes and unofficial modifications are feature-gated, just as this PR does.

2025-02-14 23:22 UTC, AlfioEmanueleFresta commented on src/resolvers/default.rs
> +    privkey: [u8; 32],
I gave this a try again, as I couldn't remember why - it seems it's not trivial:

```
error[E0515]: cannot return reference to temporary value
   --> src/resolvers/default.rs:241:9
    |
241 |         &self.pubkey.to_sec1_bytes()
    |         ^---------------------------
    |         ||
    |         |temporary value created here
    |         returns a reference to data owned by the current function

```

The issue is that the `Dh` trait requires exporting slices:

```rust
pub trait Dh: Send + Sync {
    fn pubkey(&self) -> &[u8];
    fn privkey(&self) -> &[u8];
```

However, `p256::SecretKey` and `p256::PublicKey` only return owned types (eg. `FieldBytes<...>`, or `GenericArray<u8, ...>`).

Pre-serializing the keys to their byte representation allows keeping the trait unchanged.

2025-02-14 23:40 UTC, AlfioEmanueleFresta commented on src/resolvers/default.rs
> +        );
I honestly do not recall, so I've replaced these with the test vectors from RFC 5903, and added some comments to this effect.

2025-02-14 23:48 UTC, AlfioEmanueleFresta commented
Thanks for the review @mcginty! Addressed your comments.

@complexspaces that's interesting! FWIW, here are some reasons P-256 might have been chosen for the FIDO specs: https://github.com/fido-alliance/discussions/issues/2#issuecomment-2389676305

2025-02-15 01:24 UTC, complexspaces commented on src/resolvers/default.rs
> +    privkey: [u8; 32],
I also took a quick look and agree this isn't a simple drop-in; the key types available only provide copied-array access to the inner bytes because they are stored as a "generic" field representation.

FWIW I have run into similar issues before with the use of slices for everything in the `Dh` implementations. It was when attempting to add support for ECDH directly in the _ring_ provider because those also don't (at all) provide access to a slice representation of private keys.

2025-02-15 01:26 UTC, complexspaces commented
@AlfioEmanueleFresta Yeah it makes a lot of sense why they picked P-256, including the reasons listed in your link. I don't think it was done harmfully to be clear, just out of necessity for what algorithms existing key APIs supported across OSes.

2025-02-17 22:54 UTC, mcginty approved these changes
Looks great, thank you very much for making the change and patience in needing to ping me to review it :).

2025-02-17 22:59 UTC, merged